//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storeManager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Motto { get; set; }
        public string CompanyAddress { get; set; }
        public string LandLine { get; set; }
        public string Mobile { get; set; }
        public byte[] Logo { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Fax { get; set; }
        public string MiscInfo { get; set; }
    }
}
