//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storeManager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerPaymentHistory
    {
        public int ID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public decimal PayAmount { get; set; }
        public decimal Balance { get; set; }
        public System.DateTime PaymentDate { get; set; }
    }
}
