//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storeManager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Products = new HashSet<Product>();
        }
    
        public string SupplierNum { get; set; }
        public string Name { get; set; }
        public string ContactPerson { get; set; }
        public string PostalAddress { get; set; }
        public string LocationAdress { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string PhoneNumber3 { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> SupplierSince { get; set; }
        public string Salutation { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int SupplierID { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}
