//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storeManager.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public string CompanyNum { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PhoneLine1 { get; set; }
        public string PhoneLine2 { get; set; }
        public string PhoneLine3 { get; set; }
        public string Motto { get; set; }
        public byte[] Logo { get; set; }
        public string Location { get; set; }
        public string FaxNumber { get; set; }
        public string Email { get; set; }
        public int CompanyID { get; set; }
        public string Misc { get; set; }
        public Nullable<int> DefaultLocation { get; set; }
        public string WebSite { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    }
}
