//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storeManager.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string EmployeeNum { get; set; }
        public string FisrtName { get; set; }
        public string OtherNames { get; set; }
        public string Sex { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string PhoneNumber3 { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string JobTitle { get; set; }
        public string StoreID { get; set; }
        public Nullable<int> CardID { get; set; }
        public int EmployeeID { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> EmployeeSince { get; set; }
        public string ContactPerson { get; set; }
    }
}
