//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storeManager.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ErrorLogID { get; set; }
        public string CustomMessage { get; set; }
        public string ExceptionStackTrace { get; set; }
        public string ExceptionMessage { get; set; }
        public string InnerExeptionMessage { get; set; }
        public string InnerExceptionStackTrace { get; set; }
        public Nullable<System.DateTime> ExceptionDate { get; set; }
        public string ControlName { get; set; }
        public string FormName { get; set; }
    }
}
