//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storeManager.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductLocations = new HashSet<ProductLocation>();
        }
    
        public string Barcode { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public int CategoryID { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public decimal SellingPrice { get; set; }
        public byte[] ProductImage { get; set; }
        public Nullable<bool> OnSale { get; set; }
        public int SupplierID { get; set; }
        public string ProductNum { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> LastDateAdjusted { get; set; }
        public string EmployeeID { get; set; }
        public int BrandID { get; set; }
        public string AdjustmentReason { get; set; }
        public int ProductID { get; set; }
        public int LocationID { get; set; }
        public int MeasurementID { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Measurement Measurement { get; set; }
        public virtual ICollection<ProductLocation> ProductLocations { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
