//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storeManager.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public Sale()
        {
            this.SaleDetails = new HashSet<SaleDetail>();
        }
    
        public string InvoiceNumber { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public string CustomerID { get; set; }
        public Nullable<int> SaleTypeID { get; set; }
        public string InvoiceState { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<System.DateTime> PromisedDate { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string CustomerPO { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public Nullable<bool> VoidSale { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<int> SaleStatusID { get; set; }
        public int SaleID { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<decimal> CustBalance { get; set; }
    
        public virtual ICollection<SaleDetail> SaleDetails { get; set; }
    }
}
