//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace storeManager.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleDetail
    {
        public string InvoiceNumber { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public int SalesDetailsID { get; set; }
        public string ProductID { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public int SaleID { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public Nullable<int> LocationID { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
